name: dl2020
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pip:
    - pytorch-lightning==1.0.3
    - torchtext==0.7.0
    - seaborn==0.11.0
    - tensorboard==2.3.0
    - tabulate==0.8.7
    - tqdm==4.50.2
    - pillow==8.0.1
